// Code generated by datastore. DO NOT EDIT.

package db

import (
	"github.com/jackc/pgtype/pgxtype"
	"github.com/jackc/pgx/v4/pgxpool"
)

type DBTX interface {
	pgxtype.Querier
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

type Queries struct {
	db DBTX
}

func (q *Queries) WithTx(tx *pgxpool.Tx) *Queries {
	return &Queries{
		db: tx,
	}
}
