// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
)

type Querier interface {
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	GetAccountByEmail(ctx context.Context, email string) (Account, error)
	GetAccountById(ctx context.Context, id string) (Account, error)
	ListAccounts(ctx context.Context, arg ListAccountsParams) ([]Account, error)
	UpdateAccountEmailVerificationByEmail(ctx context.Context, arg UpdateAccountEmailVerificationByEmailParams) (Account, error)
	UpdateAccountEmailVerificationByID(ctx context.Context, arg UpdateAccountEmailVerificationByIDParams) (Account, error)
	UpdateAccountPasswordByEmail(ctx context.Context, arg UpdateAccountPasswordByEmailParams) error
}

var _ Querier = (*Queries)(nil)
