GET http://localhost:8080/health

###
POST http://localhost:8080/users
Accept: application/json
Content-Type: application/json

{
    "name": "Sammi Aldhi Yanto",
    "email": "sammidev2@gmail.com",
    "gender": "MALE",
    "password": "test",
    "birthday": "2001-10-20"
}

###
POST http://localhost:8080/users/login
Accept: application/json
Content-Type: application/json

{
    "email": "sammidev2@gmail.com",
    "password": "test"
}

###
POST http://localhost:8080/playlist-category
Accept: application/json
Authorization: Bearer v2.local.Jxn2Aa5Y7SIguSAoR5PkwoC2yR1RWdRE-YT6fyEXZBR7IjQ9NTuwTz59_fO8RuPtn0xKHmjiUUl7y81QCbuue5wFjIW7yHCeveyP6z7l7BsJaju-PKGp3zXlk0SmdXUCopOoAB297usra1RY5pA-L02szkgHjHz_npvJWe7xZxZZhIZanrn1amQcy6vhEDeDLzxfGEsFbRLok4yWMs1mzlR_79MeMmrIW8OHAAeMPD3PXy9Pv9wpobKWQtDVdJZZFRxWSEO3BHQ_fG-WlHq61CVsqCXKKcEv3_o.bnVsbA